
name:  reactive-solar-fleet-prod

services:

  ms-position-write-db:
    image: mongo:8.0.3-noble
    container_name: ms-position-write-db
    environment:
      MONGO_INITDB_DATABASE: mongo-write-db
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS_WRITE}
    networks:
      - reactive-solar-fleet-net
    ports:
      - 27017:27017 
    restart: on-failure:3
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok'"
      interval: 5s
      timeout: 5s
      retries: 3

  ms-position-read-db:
    image: postgres:17.1-alpine
    container_name: ms-position-read-db
    environment:
       POSTGRES_PASSWORD: ${SQLDB_PASS}
       POSTGRES_USER: root
       POSTGRES_DB: positionReadDb
    volumes:
      - ./database/ms-position/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reactive-solar-fleet-net
    ports:
      - 5432:5432
    restart: on-failure:3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
       
  ms-position-redis-db:
    image: redis:7.4-alpine
    container_name: ms-position-redis-db
    networks:
      - reactive-solar-fleet-net
    ports:
      - 6379:6379
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      
  ms-shipclass-write-db:
    image: mongo:8.0.3-noble
    container_name: ms-shipclass-write-db
    environment:
      MONGO_INITDB_DATABASE: mongo-write-db
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS_WRITE}    
    networks:
      - reactive-solar-fleet-net
    ports:
      - 27018:27017
    restart: on-failure:3
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok'"
      interval: 5s
      timeout: 5s
      retries: 3
  
  ms-shipclass-read-db:
    image: postgres:17.1-alpine
    container_name: ms-shipclass-read-db
    environment:
       POSTGRES_PASSWORD: ${SQLDB_PASS}
       POSTGRES_USER: root
       POSTGRES_DB: shipclassReadDb
    volumes:
      - ./database/ms-shipclass/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
     - reactive-solar-fleet-net
    ports:
      - 5433:5432
    restart: on-failure:3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5  	
      
  ms-shipclass-redis-db:
    image: redis:7.4-alpine
    container_name: ms-shipclass-redis-db
    networks:
      - reactive-solar-fleet-net
    ports:
      - 6380:6379
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      
  ms-spacecraft-write-db:
    image: mongo:8.0.3-noble
    container_name: ms-spacecraft-write-db
    environment:
      MONGO_INITDB_DATABASE: mongo-write-db
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS_WRITE}
    networks:
      - reactive-solar-fleet-net
    ports:
      - 27019:27017
    restart: on-failure:3
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok'"
      interval: 5s
      timeout: 5s
      retries: 3 
  
  ms-spacecraft-read-db:
    image: postgres:17.1-alpine
    container_name: ms-spacecraft-read-db
    environment:
       POSTGRES_PASSWORD: ${SQLDB_PASS}
       POSTGRES_USER: root
       POSTGRES_DB: spacecraftReadDb    
    volumes:
      - ./database/ms-spacecraft/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reactive-solar-fleet-net
    ports:
      - 5434:5432
    restart: on-failure:3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5	
    
  ms-spacecraft-redis-db:
    image: redis:7.4-alpine
    container_name: ms-spacecraft-redis-db
    networks:
      - reactive-solar-fleet-net
    ports:
      - 6381:6379
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ] 
         
  ms-crewmember-write-db:
    image: mongo:8.0.3-noble
    container_name: ms-crewmember-write-db
    environment:
      MONGO_INITDB_DATABASE: mongo-write-db
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS_WRITE}
    networks:
      - reactive-solar-fleet-net
    ports:
      - 27020:27017
    restart: on-failure:3
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok'"
      interval: 5s
      timeout: 5s
      retries: 3 
  
  ms-crewmember-read-db:
    image: postgres:17.1-alpine
    container_name: ms-crewmember-read-db
    environment:
       POSTGRES_PASSWORD: ${SQLDB_PASS}
       POSTGRES_USER: root
       POSTGRES_DB: crewmemberReadDb    
    volumes:
      - ./database/ms-crewmember/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reactive-solar-fleet-net
    ports:
      - 5435:5432
    restart: on-failure:3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5	
    
  ms-crewmember-redis-db:
    image: redis:7.4-alpine
    container_name: ms-crewmember-redis-db
    networks:
      - reactive-solar-fleet-net
    ports:
      - 6382:6379
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]  
   
     
  kafka:
    image: bitnami/kafka:3.8
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=kusuriya-kafka
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes    
      - KAFKA_AUTO_OFFSET_RESET=earliest       
      - BITNAMI_DEBUG=true        
#    volumes:
#      - kafka_persistent:/var/lib/kafka
    networks:
      - reactive-solar-fleet-net
    ports:
      - 9092:9092
      - 9093:9093
    restart: on-failure:3
    healthcheck:
      test: "bash -c 'printf \"\" > /dev/tcp/127.0.0.1/9092; exit $$?;'"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  
  kafka-data-init:
    build: ./database/ms-kafka
    container_name: kafka-data-init
    volumes:
      - ./database/ms-kafka/init-kafka.sh:/init-kafka.sh
    command: ["/bin/bash", "/init-kafka.sh", "9092"]
    networks:
      - reactive-solar-fleet-net    
    depends_on:
      kafka:
        condition: service_healthy
        
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kusuriya-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - reactive-solar-fleet-net
    ports:
      - 8080:8080
    restart: on-failure:3    
    depends_on:
      kafka:
        condition: service_healthy

  ms-position:
    build: ./ms-position
    container_name: ms-position
    env_file: ./.env   
    environment: 
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - reactive-solar-fleet-net
    ports:
      - 8081:8081
    restart: on-failure:3
    depends_on:
      ms-position-read-db:
        condition: service_healthy
      ms-position-write-db:
        condition: service_healthy
      ms-position-redis-db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  ms-shipclass:
    build: ./ms-shipclass
    container_name: ms-shipclass
    env_file: ./.env   
    environment: 
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - reactive-solar-fleet-net
    ports:
      - 8082:8082
    restart: on-failure:3
    depends_on:
      ms-shipclass-read-db:
        condition: service_healthy
      ms-shipclass-write-db:
        condition: service_healthy
      ms-shipclass-redis-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
         
  ms-spacecraft:
    build: ./ms-spacecraft
    container_name: ms-spacecraft
    env_file: ./.env   
    environment: 
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - reactive-solar-fleet-net
    ports:
      - 8083:8083
    restart: on-failure:3
    depends_on:
      ms-spacecraft-read-db:
        condition: service_healthy
      ms-spacecraft-write-db:
        condition: service_healthy
      ms-spacecraft-redis-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
        
  ms-crewmember:
    build: ./ms-crewmember
    container_name: ms-crewmember
    env_file: ./.env   
    environment: 
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - reactive-solar-fleet-net
    ports:
      - 8084:8084
    restart: on-failure:3
    depends_on:
      ms-crewmember-read-db:
        condition: service_healthy
      ms-crewmember-write-db:
        condition: service_healthy
      ms-crewmember-redis-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
  
  ms-oauth2:
    build: ./ms-oauth2
    container_name: ms-oauth2
    environment: 
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - reactive-solar-fleet-net
    ports:
      - 9000:9000
    restart: on-failure:3
                             
       
networks:
  reactive-solar-fleet-net:
    name: reactive-solar-fleet-net
    ipam:
      config:
        - subnet: 172.20.33.0/24
          gateway: 172.20.33.1
          
          