
spring: 
  kafka:
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092 
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ms-oauth2:9000 
       
  data:
                     
    mongodb:
      uri: mongodb://sa:${MONGODB_PASS_WRITE:invalidPassword}@ms-crewmember-write-db:27017/mongo-write-db?authSource=admin
 
    redis:
      host: ms-crewmember-redis-db
      port: 6379 
 
  r2dbc:
    host: ms-crewmember-read-db
    port: 5432